from typing import TypedDict

DefiSafetyProcotol = TypedDict('DefiSafetyProcotol', {
    'quarry': str,
    'defi saver': str,
    'marinade': str,
    'uniswap v3': str,
    'bitdao': str,
    'ref finance': str,
    'opyn v2': str,
    'katana.so': str,
    'beefy.finance': str,
    'balancer v2': str,
    'venus': str,
    'gmx': str,
    'hop': str,
    'alpaca finance': str,
    'quickswap': str,
    'dopex': str,
    'stargate ': str,
    'raydium': str,
    'aperture finance ': str,
    'ribbon finance': str,
    'lido': str,
    'compound': str,
    'solace': str,
    'notional finance': str,
    'renvm': str,
    'goldfinch': str,
    'gnosis safe': str,
    'unifi': str,
    'biswap': str,
    'hats finance': str,
    'solend': str,
    'reaper farm': str,
    'orca': str,
    'tulip protocol': str,
    'serum dex': str,
    'pangolin': str,
    'mstable': str,
    'grim finance': str,
    'c.r.e.a.m finance v2': str,
    'multichain.org': str,
    'aave v3': str,
    'liquity': str,
    'defrost finance': str,
    'tomb finance': str,
    'origin': str,
    'stakedao': str,
    'solidex': str,
    'tarot': str,
    'pooltogether v4': str,
    'tornado cash': str,
    'frax': str,
    'padswap': str,
    'set protocol': str,
    'yearn': str,
    'saddle finance': str,
    'element finance': str,
    'allbridge': str,
    'astroport': str,
    'convex': str,
    'inverse finance': str,
    'geist': str,
    'trisolaris': str,
    'spookyswap': str,
    'spiritswap': str,
    'platypus finance': str,
    'gearbox protocol': str,
    'curve finance': str,
    'katana': str,
    'tranchess': str,
    'wonderland': str,
    'defikingdoms': str,
    'mirror finance': str,
    'impermax finance': str,
    'trader joe': str,
    'sushiswap  v2': str,
    'alpha homora v2': str,
    'vvs': str,
    'paint swap': str,
    'bsc station': str,
    'solarbeam': str,
    'beethovenx': str,
    'klimadao': str,
    'planet finance': str,
    'benqi': str,
    'premia finance': str,
    'truefi v4': str,
    'tetu ': str,
    'cafe swap': str,
    'maple finance': str,
    'honeyfarm 2.0': str,
    'shapeshift': str,
    'makerdao': str,
    'tokemak': str,
    'tracer finance': str,
    'abracadabra.money': str,
    'babyswap': str,
    'keep3r v2': str,
    'popsicle finance': str,
    'hegic v8888': str,
    'idle v4': str,
    'loopring v3': str,
    'bagels finance': str,
    'harvest finance v2': str,
    'dodo exchange v2': str,
    'olympus finance': str,
    'piedao': str,
    'moola': str,
    '0x protocol': str,
    'ubeswap': str,
    'cowswap': str,
    'badger finance': str,
    'dhedge v2': str,
    'instadapp v2  update': str,
    'openocean': str,
    'akropolis': str,
    'ilayer': str,
    '88mph v3.0': str,
    'nexus mutual  ': str,
    'kyber network 3.0': str,
    'defi swap (crypto.com)': str,
    'bzx v2': str,
    'pancake hunny': str,
    'kine protocol': str,
    'autoshark finance': str,
    'gravity finance': str,
    'shibaswap v3': str,
    'keep network': str,
    'dydx layer 2': str,
    'dinoswap': str,
    '1inch.exchange': str,
    'bunnypark': str,
    'insurace': str,
    'pylon protocol': str,
    'terraswap': str,
    'kalmar': str,
    'snowball finance': str,
    'helmet.insure': str,
    'yearn finance v2': str,
    'ampleforth': str,
    'bancor': str,
    'aave v2': str,
    'mai finance': str,
    'feg exchange': str,
    'orion protocol': str,
    'o3 swap': str,
    'pancake bunny': str,
    'polycat finance': str,
    'rabbit finance': str,
    'stakewise': str,
    'ellipsis finance': str,
    'anchor protocol': str,
    'paraswap': str,
    'privacyswap': str,
    'jetfuel finance': str,
    'pancakeswap': str,
    'jetswap': str,
    'belt finance': str,
    'treedefi': str,
    'wing finance': str,
    'ramp': str,
    'autofarm': str,
    'dfyn': str,
    'apeswap': str,
    'quickswap process quality review': str,
    'pickle finance v2': str,
    'kebab finance': str,
    'barnbridge': str,
    'uma project': str,
    'unfederalreserve': str,
    'growthdefi': str,
    'macaronswap': str,
    'convex finance': str,
    'graviton.one': str,
    'acryptos': str,
    'nerve.fi': str,
    'armor.fi': str,
    'wault finance': str,
    'yaxis': str,
    'reflexer finance': str,
    'bao.finance': str,
    'idex.io': str,
    'peakdefi pq': str,
    'synthetix pq': str,
    'defi bids ': str,
    'perpetual protocol': str,
    'cover protocol': str,
    'vesper': str,
    'value defi': str,
    'perlinx': str,
    'enzyme': str,
    'definer': str,
    'augur': str,
    'ddex': str,
    'saffron finance': str,
    'wise': str,
    'unitrade': str,
    'plotx': str,
    'dracula': str,
    'dforce': str,
    'cyclone protocol': str,
})

protocol: DefiSafetyProcotol = {
    'quarry': 'Quarry',
    'defi saver': 'Defi Saver',
    'marinade': 'Marinade',
    'uniswap v3': 'Uniswap V3',
    'bitdao': 'BitDAO',
    'ref finance': 'Ref Finance',
    'opyn v2': 'Opyn V2',
    'katana.so': 'Katana.so',
    'beefy.finance': 'Beefy.finance',
    'balancer v2': 'Balancer V2',
    'venus': 'Venus',
    'gmx': 'GMX',
    'hop': 'Hop',
    'alpaca finance': 'Alpaca Finance',
    'quickswap': 'Quickswap',
    'dopex': 'Dopex',
    'stargate ': 'Stargate ',
    'raydium': 'Raydium',
    'aperture finance ': 'Aperture Finance ',
    'ribbon finance': 'Ribbon Finance',
    'lido': 'Lido',
    'compound': 'Compound',
    'solace': 'Solace',
    'notional finance': 'Notional Finance',
    'renvm': 'RenVM',
    'goldfinch': 'Goldfinch',
    'gnosis safe': 'Gnosis Safe',
    'unifi': 'UniFi',
    'biswap': 'Biswap',
    'hats finance': 'Hats Finance',
    'solend': 'Solend',
    'reaper farm': 'Reaper Farm',
    'orca': 'Orca',
    'tulip protocol': 'Tulip Protocol',
    'serum dex': 'Serum DEX',
    'pangolin': 'Pangolin',
    'mstable': 'mStable',
    'grim finance': 'Grim Finance',
    'c.r.e.a.m finance v2': 'C.R.E.A.M Finance v2',
    'multichain.org': 'Multichain.org',
    'aave v3': 'Aave V3',
    'liquity': 'Liquity',
    'defrost finance': 'Defrost finance',
    'tomb finance': 'Tomb Finance',
    'origin': 'Origin',
    'stakedao': 'StakeDAO',
    'solidex': 'Solidex',
    'tarot': 'Tarot',
    'pooltogether v4': 'PoolTogether v4',
    'tornado cash': 'Tornado Cash',
    'frax': 'Frax',
    'padswap': 'PadSwap',
    'set protocol': 'Set Protocol',
    'yearn': 'Yearn',
    'saddle finance': 'Saddle Finance',
    'element finance': 'Element Finance',
    'allbridge': 'Allbridge',
    'astroport': 'Astroport',
    'convex': 'Convex',
    'inverse finance': 'Inverse Finance',
    'geist': 'Geist',
    'trisolaris': 'TriSolaris',
    'spookyswap': 'SpookySwap',
    'spiritswap': 'SpiritSwap',
    'platypus finance': 'Platypus Finance',
    'gearbox protocol': 'Gearbox Protocol',
    'curve finance': 'Curve Finance',
    'katana': 'Katana',
    'tranchess': 'Tranchess',
    'wonderland': 'Wonderland',
    'defikingdoms': 'DeFiKingdoms',
    'mirror finance': 'Mirror Finance',
    'impermax finance': 'Impermax Finance',
    'trader joe': 'Trader Joe',
    'sushiswap  v2': 'SushiSwap  v2',
    'alpha homora v2': 'Alpha Homora V2',
    'vvs': 'VVS',
    'paint swap': 'Paint Swap',
    'bsc station': 'BSC Station',
    'solarbeam': 'Solarbeam',
    'beethovenx': 'BeethovenX',
    'klimadao': 'KlimaDAO',
    'planet finance': 'Planet Finance',
    'benqi': 'benQi',
    'premia finance': 'Premia Finance',
    'truefi v4': 'TrueFi V4',
    'tetu ': 'Tetu ',
    'cafe swap': 'Cafe Swap',
    'maple finance': 'Maple Finance',
    'honeyfarm 2.0': 'HoneyFarm 2.0',
    'shapeshift': 'ShapeShift',
    'makerdao': 'MakerDAO',
    'tokemak': 'Tokemak',
    'tracer finance': 'Tracer Finance',
    'abracadabra.money': 'Abracadabra.money',
    'babyswap': 'BabySwap',
    'keep3r v2': 'Keep3r V2',
    'popsicle finance': 'Popsicle Finance',
    'hegic v8888': 'Hegic V8888',
    'idle v4': 'Idle v4',
    'loopring v3': 'Loopring V3',
    'bagels finance': 'Bagels Finance',
    'harvest finance v2': 'Harvest Finance V2',
    'dodo exchange v2': 'DODO Exchange V2',
    'olympus finance': 'Olympus Finance',
    'piedao': 'PieDAO',
    'moola': 'Moola',
    '0x protocol': '0x Protocol',
    'ubeswap': 'UbeSwap',
    'cowswap': 'Cowswap',
    'badger finance': 'Badger Finance',
    'dhedge v2': 'dHEDGE v2',
    'instadapp v2  update': 'Instadapp v2  UPDATE',
    'openocean': 'OpenOcean',
    'akropolis': 'Akropolis',
    'ilayer': 'iLayer',
    '88mph v3.0': '88mph V3.0',
    'nexus mutual  ': 'Nexus Mutual  ',
    'kyber network 3.0': 'Kyber Network 3.0',
    'defi swap (crypto.com)': 'DeFi Swap (Crypto.com)',
    'bzx v2': 'bZx v2',
    'pancake hunny': 'Pancake Hunny',
    'kine protocol': 'Kine Protocol',
    'autoshark finance': 'AutoShark Finance',
    'gravity finance': 'Gravity Finance',
    'shibaswap v3': 'ShibaSwap V3',
    'keep network': 'Keep Network',
    'dydx layer 2': 'dYdX Layer 2',
    'dinoswap': 'DinoSwap',
    '1inch.exchange': '1inch.exchange',
    'bunnypark': 'BunnyPark',
    'insurace': 'InsurAce',
    'pylon protocol': 'Pylon Protocol',
    'terraswap': 'Terraswap',
    'kalmar': 'Kalmar',
    'snowball finance': 'Snowball Finance',
    'helmet.insure': 'Helmet.insure',
    'yearn finance v2': 'Yearn Finance V2',
    'ampleforth': 'Ampleforth',
    'bancor': 'Bancor',
    'aave v2': 'AAVE V2',
    'mai finance': 'Mai Finance',
    'feg exchange': 'FEG Exchange',
    'orion protocol': 'Orion Protocol',
    'o3 swap': 'O3 Swap',
    'pancake bunny': 'Pancake Bunny',
    'polycat finance': 'Polycat Finance',
    'rabbit finance': 'Rabbit Finance',
    'stakewise': 'StakeWise',
    'ellipsis finance': 'Ellipsis Finance',
    'anchor protocol': 'Anchor Protocol',
    'paraswap': 'ParaSwap',
    'privacyswap': 'PrivacySwap',
    'jetfuel finance': 'Jetfuel Finance',
    'pancakeswap': 'PancakeSwap',
    'jetswap': 'Jetswap',
    'belt finance': 'Belt Finance',
    'treedefi': 'TreeDefi',
    'wing finance': 'Wing Finance',
    'ramp': 'RAMP',
    'autofarm': 'AutoFarm',
    'dfyn': 'DFYN',
    'apeswap': 'ApeSwap',
    'quickswap process quality review': 'QuickSwap Process Quality Review',
    'pickle finance v2': 'Pickle Finance V2',
    'kebab finance': 'Kebab Finance',
    'barnbridge': 'BarnBridge',
    'uma project': 'UMA Project',
    'unfederalreserve': 'unFederalReserve',
    'growthdefi': 'GrowthDefi',
    'macaronswap': 'MacaronSwap',
    'convex finance': 'Convex Finance',
    'graviton.one': 'Graviton.one',
    'acryptos': 'ACryptoS',
    'nerve.fi': 'Nerve.fi',
    'armor.fi': 'Armor.fi',
    'wault finance': 'Wault Finance',
    'yaxis': 'yAxis',
    'reflexer finance': 'Reflexer Finance',
    'bao.finance': 'Bao.Finance',
    'idex.io': 'Idex.io',
    'peakdefi pq': 'PEAKDEFI PQ',
    'synthetix pq': 'Synthetix PQ',
    'defi bids ': 'Defi Bids ',
    'perpetual protocol': 'Perpetual Protocol',
    'cover protocol': 'Cover Protocol',
    'vesper': 'Vesper',
    'value defi': 'Value Defi',
    'perlinx': 'PerlinX',
    'enzyme': 'Enzyme',
    'definer': 'DeFiner',
    'augur': 'Augur',
    'ddex': 'DDex',
    'saffron finance': 'Saffron Finance',
    'wise': 'Wise',
    'unitrade': 'Unitrade',
    'plotx': 'PlotX',
    'dracula': 'Dracula',
    'dforce': 'dForce',
    'cyclone protocol': 'Cyclone Protocol',
}
